### ISSUE TITLE
something I dont understand but happend after I placed a Gold Ore Block

### ISSUE THREAD

**Issue by Kelemvore** [wyldmods/WyldCraftIssues#40]
Here is the crash report but I my client keeps crashing when I get near where I placed a gold ore block on the Wylds sub server today... and now im in a crash loop

java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!

```
at net.minecraft.entity.ai.attributes.RangedAttribute.<init>(SourceFile:14)
at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:1629)
at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:71)
at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:15)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
at java.lang.reflect.Method.invoke(-1)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

I dont know my coords either or I would have posted them for someone to go regen the area or whatever but either way I dont want to lose some items I have in my chest  but I also want to play dag nabit lol

**Comment by tterrag1098** [comment]
Please post the entire crash log. Use a site like http://pastebin.com or http://gist.github.com

**Comment by Kelemvore** [comment]
here ya go.  I copied the other report straight from Open Eye but this is the entire report  http://pastebin.com/EQAXHUU0
